---
title: "Net-Map Institucional. Trata y tráfico en Bolivia"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    social: [ "twitter", "facebook", "menu" ]
    navbar:
      - { title: "Fundación Aru", href: "https://aru.org.bo", align: right }
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Introducción  {.sidebar}
===============================================================

### Acerca del proyecto

Este dashboard fue desarrollado dentro del proyecto que llevó adelante Fundación Aru para la OIM-Bolivia

### Contenido 
  
  * Netmap interactivo
  * Tabla con las instituciones identificadas en el estudio


### Desarrollado por
Fundación Aru

# Red Interactiva

```{r}
rm(list=ls())
###################################################
library(readxl)
library(igraph)
library(sp)
library(leaflet)
library(visNetwork) 
###################################################
oim_v<-read_excel("/Users/iMac6/Desktop/_ARU2020/1_OIM_trata/docs/entidades.xlsx",1,skip=1)
oim_l<-read_excel("/Users/iMac6/Desktop/_ARU2020/1_OIM_trata/docs/entidades.xlsx",2)

netmap <- graph_from_data_frame(d=oim_l, vertices=oim_v, directed=T)
colrs <- c("pink","green","orange","skyblue")
ltent=c("Pública","ONG","Cooperacción","Organizaciones Sociales")
set.seed(777)
V(netmap)$color <- colrs[V(netmap)$itent]
data <- toVisNetworkData(netmap)
nodes = data$nodes; edges = data$edges
nodes$size<-nodes$w^2.5+10
nodes$label<-nodes$entidad
set.seed(777)
visNetwork(nodes,edges) %>% visEdges(arrows = "to")
```

# Instituciones

```{r}
library(knitr)
t1<-oim_v[,2:3]
kable(t1[order(t1[,2]),],col.names=c("Entidad","Tipo"))
```

